"""Update project model

Revision ID: 73d86780ed34
Revises: 73f025b38d16
Create Date: 2026-06-30 23:43:33.837195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d86780ed34'
down_revision: Union[str, None] = '73f025b38d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('projects', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('company_stage', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('decision_type', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('projects', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('projects', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'decision_type')
    op.drop_column('projects', 'company_stage')
    op.drop_column('projects', 'industry')
    op.drop_column('projects', 'title')
    # ### end Alembic commands ###
